services:
  app:
    build:
      context: .
      target: development-dependencies-env
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:5173"
    env_file: .env
